# Generated by Django 2.2.1 on 2019-07-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vedio',
            old_name='course',
            new_name='lesson',
        ),
    ]
